(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var e,f=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");},g=f(this),h="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b},k;
if("function"==typeof Object.setPrototypeOf)k=Object.setPrototypeOf;else{var l;a:{var m={a:!0},n={};try{n.__proto__=m;l=n.a;break a}catch(a){}l=!1}k=l?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}
var p=k,q=this||self,r=Date.now,t=function(a,b){a=a.split(".");var c=q;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b};Object.freeze&&Object.freeze([]);try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};var u=function(a,b){var c=(c=q.performance)&&c.now&&c.timing?Math.floor(c.now()+c.timing.navigationStart):r();a={label:a,type:9,value:c};b=b.google_js_reporting_queue=b.google_js_reporting_queue||[];2048>b.length&&b.push(a)};var v={},w=!1,x=!1;v.s=function(a){w||(w=!0,u("11",a))};v.u=function(a){x||(x=!0,u("12",a))};v.o=function(a,b,c){c=void 0===c?0:c;var d=b;d=void 0===d?q:d;if(d=(d=d.performance)&&d.now?d.now():null)a={label:a,type:c,value:d},b=b.google_js_reporting_queue=b.google_js_reporting_queue||[],2048>b.length&&b.push(a)};v.reset=function(a){x=w=!1;(a.google_js_reporting_queue=a.google_js_reporting_queue||[]).length=0};t("gwd.rumUtil",v);t("gwd.rumUtil.logContentLoading",v.s);
t("gwd.rumUtil.logContentRendered",v.u);t("gwd.rumUtil.logTimingEvent",v.o);t("gwd.rumUtil.reset",v.reset);var y=function(a){(0,v.o)("gwd3dmodel_"+(a?"start":"stop")+"Timer_TimeToFirstFrame",window);a?Enabler.startTimer("TimeToFirstFrame"):Enabler.stopTimer("TimeToFirstFrame")},A=function(a){a?Enabler.startTimer("TotalEngagement"):Enabler.stopTimer("TotalEngagement");z()},B=0,C=0;function z(){var a=performance.now();a=Math.floor(a/100);0==B&&(B=a);for(a-=B;C<=a;C++)Enabler.counter("TotalSessionDurationDeciseconds",!0)}
var D={Engagement:function(){Enabler.reportEngagement()},Zoom:function(){Enabler.counter("Zoom",!0)},Pan:function(){Enabler.counter("Pan",!0)},Rotate:function(){Enabler.counter("Rotate",!0)},Hotspot1Click:function(){Enabler.counter("Hotspot1Click",!0)},Hotspot2Click:function(){Enabler.counter("Hotspot2Click",!0)},Hotspot3Click:function(){Enabler.counter("Hotspot3Click",!0)},Hotspot4Click:function(){Enabler.counter("Hotspot4Click",!0)},Hotspot5Click:function(){Enabler.counter("Hotspot5Click",!0)}},
E={};var F=function(a,b,c){c=void 0===c?null:c;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,c);b.dispatchEvent(d)};var G=["glass","gesture-cue-icon","gesture-cue-text","src","transparent"],H=function(){var a=HTMLElement.call(this)||this;a.h=null;a.j=!1;return a},I=HTMLElement;H.prototype=h(I.prototype);H.prototype.constructor=H;if(p)p(H,I);else for(var J in I)if("prototype"!=J)if(Object.defineProperties){var K=Object.getOwnPropertyDescriptor(I,J);K&&Object.defineProperty(H,J,K)}else H[J]=I[J];
H.prototype.connectedCallback=function(){window.Enabler&&(Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this),Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this));L(this)};
H.prototype.disconnectedCallback=function(){window.Enabler&&(Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this),Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this));this.i&&(clearTimeout(this.i),this.i=void 0)};H.prototype.attributeChangedCallback=function(){L(this)};
H.prototype.handleEvent=function(a){var b=this,c=a.type,d=a.detail;switch(c){case "click":(this.m||this.l)&&a.target===this.f&&a.stopPropagation();break;case "start-timer":case "stop-timer":M(this,d.timer,"start-timer"===c);break;case "scene-rendered":case "camera-changed":a.stopPropagation();F(c,this,d);break;case "hotspot-clicked":this.l=!0;window.setTimeout(function(){b.l=!1},0);N(d.index);a.stopPropagation();F(c,this,d);break;case "increment-counter":O(d.counter,d.cumulative);break;case studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH:P(this).removeAttribute("scroll-gating");
Enabler.reportEngagement();z();break;case studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH:P(this).setAttribute("scroll-gating",""),z()}};
var P=function(a){a.f||(a.f=a.ownerDocument.createElement("gltf-viewer"),a.f.setAttribute("scroll-gating",""),a.f.addEventListener("start-timer",a),a.f.addEventListener("stop-timer",a),a.f.addEventListener("increment-counter",a),a.f.addEventListener("scene-rendered",a),a.f.addEventListener("camera-changed",a),a.f.addEventListener("hotspot-clicked",a),a.f.addEventListener("click",a),a.appendChild(a.f));return a.f},L=function(a){a.i||(a.i=window.setTimeout(a.gwdLoad.bind(a),0))};
H.prototype.gwdLoad=function(){this.i&&(clearTimeout(this.i),this.i=void 0);var a=this.f?this.f.getAttribute("src"):null,b=Q(this,"src",!0);if(b){if(Q(this,"transparent"),Q(this,"glass"),b!==a&&(this.j=!1,this.classList.remove("ready"),y(!0)),this.h&&this.h.parentNode&&this.h.parentNode.removeChild(this.h),b=this.getAttribute("gesture-cue-icon")){this.h=this.ownerDocument.createElement("div");this.h.classList.add("gesture-cue-container");a=this.ownerDocument.createElement("div");a.classList.add("gesture-cue-icon");
a.style.backgroundImage='url("'+b+'")';b=parseFloat(this.getAttribute("gesture-cue-duration"));isFinite(b)||(b=29);a.style.animationIterationCount=0>b?"infinite, 1":(b/2).toFixed(1)+", 1";this.h.appendChild(a);if(a=this.getAttribute("gesture-cue-text"))b=this.ownerDocument.createElement("p"),b.classList.add("gesture-cue-text"),b.textContent=a,this.h.appendChild(b);this.appendChild(this.h)}}else R(this)};H.prototype.gwdIsLoaded=function(){return this.j};
var Q=function(a,b,c){c=void 0===c?!1:c;var d=a.getAttribute(b);null==d||c&&!d?a.f&&a.f.removeAttribute(b):P(a).setAttribute(b,d);return a.f?a.f.getAttribute(b):null},R=function(a){a.j||(a.j=!0,F("ready",a))},M=function(a,b,c){c?"TotalEngagement"===b&&(a.m=!0,A(!0),F("interaction-start",a),a.h&&a.h.parentNode&&a.h.parentNode.removeChild(a.h)):"TotalEngagement"===b?(a.m=!1,A(!1),F("interaction-end",a)):"TimeToFirstFrame"===b&&(y(!1),a.classList.add("ready"),R(a))},O=function(a,b){b=b?D:E;if(b[a])b[a]()},
N=function(a){D.Engagement();a="Hotspot"+(a+1)+"Click";if(D[a])D[a]()};e=H.prototype;e.setYaw=function(a){S(this,{name:"setYaw",yawAngle:a,pauseRestingAnimation:!0})};e.setTargetYaw=function(a){S(this,{name:"setTargetYaw",yawAngle:a})};e.setTargetPitch=function(a){S(this,{name:"setTargetPitch",pitchAngle:a})};e.incrementTargetPitch=function(a){S(this,{name:"incrementTargetPitch",pitchAngle:a})};e.setTargetZoom=function(a){S(this,{name:"setTargetZoom",scale:a})};
e.incrementTargetZoom=function(a){S(this,{name:"incrementTargetZoom",scale:a})};e.setTargetPivot=function(a,b,c){S(this,{name:"setTargetPivot",X:a,Y:b,Z:c})};e.setTargetLocalPan=function(a,b){S(this,{name:"setTargetLocalPan",X:a,Y:b})};e.setMaterialColor=function(a,b,c,d){S(this,{name:"setMaterialColor",material:a,r:b,g:c,b:d})};e.setMaterialClearCoat=function(a,b,c){S(this,{name:"setMaterialClearCoat",material:a,value:b,roughness:c})};e.playAnimation=function(a){S(this,{name:"animationPlay",animationName:a})};
e.pauseAnimation=function(a){S(this,{name:"animationPause",animationName:a})};e.setAnimationTime=function(a,b){S(this,{name:"animationSetTime",animationName:a,time:b})};e.incrementAnimationTime=function(a,b){S(this,{name:"animationIncrementTime",animationName:a,time:b})};e.addHotspot=function(a,b,c,d){S(this,{name:"addHotspot",hotspotName:a,x:b,y:c,z:d})};e.setHotspotInfoCard=function(a,b,c){S(this,{name:"setHotspotInfoCard",hotspotName:a,title:b,text:c})};
e.lookAtHotspot=function(a){S(this,{name:"lookAtHotspot",hotspotName:a})};e.lookAtHotspotIndex=function(a){S(this,{name:"lookAtHotspotIndex",hotspotIndex:a})};e.handleMessage=function(a){S(this,a)};var S=function(a,b){a=P(a);a.handleMessage&&a.handleMessage(b)};g.Object.defineProperties(H,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return G}}});customElements.define("gwd-3d-model",H);}).call(this);
